# set the project name to directory name of the ansible porject
docker_compose_project: "{{ playbook_dir | basename }}"
# set the compose file template path
docker_compose_file_path: "{{ playbook_dir }}/compose-files/docker-compose.yml"
# if docker compose should pull new images first
docker_compose_pull: true

# clean the docker graph directory when using zfs
docker_compose_clean_graph: false
# delete old images
docker_compose_prune_images: false
# delete unused volumes
docker_compose_prune_volumes: false
